[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'cache_forge'
evm_version = "shanghai"
solc = "0.8.24"
optimizer_runs = 200

remappings=[
    "@openzeppelin/=./node_modules/@openzeppelin/",
    "@openzeppelin/contracts=./node_modules/@openzeppelin/contracts",
    "@openzeppelin/contracts-upgradeable=./node_modules/@openzeppelin/contracts-upgradeable",
    "@chainlink/contracts=./node_modules/@chainlink/contracts",
    "@layerzerolabs/lz-evm-protocol-v2/contracts=./node_modules/@layerzerolabs/lz-evm-protocol-v2/contracts",
    "@layerzerolabs/lz-evm-messagelib-v2/contracts=./node_modules/@layerzerolabs/lz-evm-messagelib-v2/contracts",
    "@layerzerolabs/lz-evm-oapp-v2/contracts=./node_modules/@layerzerolabs/lz-evm-oapp-v2/contracts",
    "@layerzerolabs/lz-evm-v1-0.7/contracts=./node_modules/@layerzerolabs/lz-evm-v1-0.7/contracts",
    "solidity-bytes-utils/contracts=./node_modules/solidity-bytes-utils/contracts",
]

[rpc_endpoints]
bsc-test = "${BSC_TESTNET_RPC_URL}"
bsc = "${BSC_RPC_URL}"

[etherscan]
bsc-test = { key = "${BSCSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}" }
